Fix: Long형 변수에 Date 형식 String을 넣어 발생하는 예외 해결
2024-01-24 00:46
예외 내용
org.springframework.web.method.annotation.MethodArgumentTypeMismatchException: Failed to convert value of type 'java.lang.String' to required type 'java.lang.Long'; For input string: "2024-01-24T00:43"
변경 사항
const timestamp = new Date(timeInput).getTime() / 1000;